function RC(U, R, C, f, D, N)
    fig = figure('Name', 'Circuit de integrare cu RC', ...  % inițializare figură
                 'Numbertitle', 'off', ...
                 'Color', '#f8e8cc', ...
                 'Units', 'normalized', ...
                 'Position', [0.1 0.1 0.7 0.7]);

    meniu = uimenu('Label', 'Proiect');  
    uimenu(meniu, 'Label', 'Iesire', 'Callback', 'close', 'Separator', 'on');                                       %creare meniu 
    uimenu(meniu, 'Label', 'Documentație', 'Callback',  @(src, event) open('DOCUMENTAȚIE.pdf'), 'Separator', 'on');  
    uimenu(meniu, 'Label', 'Teorie', 'Callback',  @(src, event) open('/MATLAB Drive/PROIECT/CIRCUIT INTEGRATOR  RC.pdf'), 'Separator', 'on');
    
    Titlu = uicontrol('Style', 'text', ...                              %Titlul interfeței
                      'Units', 'normalized', ...
                      'BackgroundColor', '#f8e8cc', ...
                      'ForegroundColor', '#2f2a35', ...
                      'Position', [0.01 0.85 0.35 0.1], ...
                      'String', 'Circuit de integrare cu RC', ...
                      'FontSize', 30, ...
                      'FontName', 'Helvetica', ...
                      'FontWeight', 'bold', ...
                      'HorizontalAlignment', 'center');

    CasetaParam = uipanel('Visible', 'on', ...                      %grup de butoane 1
                          'BackgroundColor', '#4D303F', ...
                          'TitlePosition', 'centertop', ...
                          'FontSize', 20, ...
                          'BorderType', 'none', ...
                          'Position', [0.05 0.5 0.25 0.35]);
    
    BTitlu1 = uicontrol('Style', 'text', ...
                        'Units', 'normalized', ...
                        'Position', [0.1 0.8 0.8 0.12], ...
                        'BackgroundColor', '#914356', ...
                        'ForegroundColor', '#2f2a35', ...
                        'String', 'Parametrii circuitului', ...
                        'Fontsize', 22, ...
                        'FontName', 'Helvetica', ...
                        'FontWeight', 'bold', ...
                        'HorizontalAlignment', 'center', ...
                        'Parent', CasetaParam);

    BRtext = uicontrol('Style', 'text', ...
                       'Units', 'normalized', ...
                       'Position', [0.1 0.5 0.35 0.08], ...
                       'BackgroundColor', '#914356', ...
                       'ForegroundColor', '#2f2a35', ...
                       'String', 'Rezistența [Ω]', ... 
                       'Fontsize', 15, ...
                       'FontName', 'Courier New', ...
                       'FontWeight', 'bold', ...
                       'HorizontalAlignment', 'center', ...
                       'Parent', CasetaParam);
                       
    BCtext = uicontrol('Style', 'text', ...
                       'Units', 'normalized', ...
                       'Position', [0.1 0.3 0.35 0.08], ...
                       'BackgroundColor', '#914356', ...
                       'ForegroundColor', '#2f2a35', ...
                       'String', 'Capacitatea [F]', ...
                       'FontWeight', 'bold', ...
                       'Fontsize', 15, ...
                       'FontName', 'Courier New', ...
                       'HorizontalAlignment', 'center', ...
                       'Parent', CasetaParam);

     
    Bcttext = uicontrol('Style', 'text', ...
                       'Units', 'normalized', ...
                       'Position', [0.1 0.1 0.35 0.08], ...
                       'BackgroundColor', '#914356', ...
                       'ForegroundColor', '#2f2a35', ...
                       'String', 'τ (R*C)', ...
                       'FontWeight', 'bold', ...
                       'Fontsize', 15, ...
                       'FontName', 'Courier New', ...
                       'HorizontalAlignment', 'center', ...
                       'Parent', CasetaParam);
                       
    BR = uicontrol('Style', 'edit', ...                                 
                   'Units', 'normalized', ...
                   'Position', [0.55 0.5 0.35 0.08], ...
                   'String', R, ...
                   'BackgroundColor', '#f8e8cc', ...
                   'Callback', @(src, event) pozitiv(src), ...
                   'Parent', CasetaParam);
    
    BC = uicontrol('Style', 'edit', ...
                   'Units', 'normalized', ...
                   'Position', [0.55 0.3 0.35 0.08], ...
                   'String', C, ...
                   'BackgroundColor', '#f8e8cc', ...
                   'Callback', @(src, event) pozitiv(src), ...
                   'Parent', CasetaParam);
    
    BTauVal = uicontrol('Style', 'text', ...
                          'Units', 'normalized', ...
                          'Position', [0.55 0.1 0.35 0.08], ...
                          'String', num2str(R * C), ...             %numarul devine un sir de caractere
                          'BackgroundColor', '#f8e8cc', ...
                          'HorizontalAlignment', 'center', ...
                          'FontWeight', 'bold', ...
                          'FontSize', 15, ...
                          'Parent', CasetaParam);
    
    CasetaSemnal = uipanel('Visible', 'on', ...                     %grup de butoane 2
                           'BackgroundColor', '#4D303F', ...
                           'TitlePosition', 'centertop', ...
                           'FontSize', 20, ...
                           'BorderType', 'none', ...
                           'Position', [0.05 0.05 0.25 0.4]);
    
    BTitlu2 = uicontrol('Style', 'text', ...
                        'Units', 'normalized', ...
                        'Position', [0.1 0.85 0.8 0.1], ...
                        'BackgroundColor', '#914356', ...
                        'ForegroundColor', '#2f2a35', ...
                        'String', 'Parametrii semnalului', ...
                        'Fontsize', 22, ...
                        'FontName', 'Helvetica', ...
                        'FontWeight', 'bold', ...
                        'HorizontalAlignment', 'center', ...
                        'Parent', CasetaSemnal);
    
    BUtext = uicontrol('Style', 'text', ...
                       'Units', 'normalized', ...
                       'Position', [0.1 0.7 0.35 0.08], ...
                       'BackgroundColor', '#914356', ...
                       'ForegroundColor', '#2f2a35', ...
                       'String', 'Tensiunea [V]', ... 
                       'Fontsize', 18, ...
                       'FontName', 'Courier New', ...
                       'FontWeight', 'bold', ...
                       'HorizontalAlignment', 'center', ...
                       'Parent', CasetaSemnal);
    
    Bftext = uicontrol('Style', 'text', ...
                       'Units', 'normalized', ...
                       'Position', [0.1 0.55 0.35 0.08], ...
                       'BackgroundColor', '#914356', ...
                       'ForegroundColor', '#2f2a35', ...
                       'String', 'Frecvența [Hz]', ... 
                       'Fontsize', 18, ...
                       'FontName', 'Courier New', ...
                       'FontWeight', 'bold', ...
                       'HorizontalAlignment', 'center', ...
                       'Parent', CasetaSemnal);
    
    BNtext = uicontrol('Style', 'text', ...
                       'Units', 'normalized', ...
                       'Position', [0.1 0.4 0.35 0.08], ...
                       'BackgroundColor', '#914356', ...
                       'ForegroundColor', '#2f2a35', ...
                       'String', 'Număr Perioade', ...
                       'FontWeight', 'bold', ...
                       'Fontsize', 18, ...
                       'FontName', 'Courier New', ...
                       'HorizontalAlignment', 'center', ...
                       'Parent', CasetaSemnal);
    
    BDutext = uicontrol('Style', 'text', ...
                       'Units', 'normalized', ...
                       'Position', [0.1 0.25 0.35 0.08], ...
                       'BackgroundColor', '#914356', ...
                       'ForegroundColor', '#2f2a35', ...
                       'String', 'Duty Factor', ...
                       'FontWeight', 'bold', ...
                       'Fontsize', 18, ...
                       'FontName', 'Courier New', ...
                       'HorizontalAlignment', 'center', ...
                       'Parent', CasetaSemnal);

    VoffsetText = uicontrol('Style', 'text', ...
                            'Units', 'normalized', ...
                            'Position', [0.1 0.1 0.35 0.08], ...
                            'BackgroundColor', '#914356', ...
                            'ForegroundColor', '#2f2a35', ...
                            'String', 'Voffset [V]', ...
                            'Fontsize', 18, ...
                            'FontName', 'Courier New', ...
                            'FontWeight', 'bold', ...
                            'HorizontalAlignment', 'center', ...
                            'Parent', CasetaSemnal);

    BU = uicontrol('Style', 'edit', ...             %tensiunea
                   'Units', 'normalized', ...
                   'Position', [0.55 0.7 0.35 0.08], ...
                   'String', U, ...
                   'BackgroundColor', '#f8e8cc', ...
                   'Callback', @(src, event) pozitiv(src), ...
                   'Parent', CasetaSemnal);
    
    BT = uicontrol('Style', 'edit', ...             %frecventa
                   'Units', 'normalized', ...
                   'Position', [0.55 0.55 0.35 0.08], ...
                   'String', f, ...
                   'BackgroundColor', '#f8e8cc', ...
                   'Callback', @(src, event) pozitiv(src), ...
                   'Parent', CasetaSemnal);
    
    BN = uicontrol('Style', 'PopupMenu', ...           %numar perioade
                   'Units', 'normalized', ...
                   'Position', [0.55 0.4 0.35 0.08], ...
                   'String', {'1', '2', '3', '4', '5'}, ...
                   'BackgroundColor', '#f8e8cc', ...
                   'Callback', @(src, event) actual(), ...
                   'Parent', CasetaSemnal);
    
    BD = uicontrol('Style', 'slide', ...                %factor umplere
                   'Units', 'normalized', ...
                   'Position', [0.55 0.25 0.35 0.08], ...
                   'Min', 0, 'Max', 100, 'Value', D, ...
                   'Callback', @(src, event) actual(), ...
                   'Parent', CasetaSemnal);

    %  uicontrol('Style', 'text', ...
    %       'Units', 'normalized', ...
    %       'Position', [0.55 0.251 0.05 0.079], ... 
    %       'BackgroundColor', 'w', ...
    %       'ForegroundColor', 'black', ...
    %       'String', num2str(get(BD, 'Min')), ...
    %       'Parent', CasetaSemnal);
    % 
    % uicontrol('Style', 'text', ...
    %       'Units', 'normalized', ...
    %       'Position', [0.85 0.251 0.05 0.079], ... 
    %       'BackgroundColor', 'w', ...
    %       'ForegroundColor', 'black', ...
    %       'String', num2str(get(BD, 'Max')), ...
    %       'Parent', CasetaSemnal);
   
    BVoff = uicontrol('Style', 'edit', ...
                        'Units', 'normalized', ...
                        'Position', [0.55 0.1 0.35 0.08], ...
                        'String', '0', ...
                        'BackgroundColor', '#f8e8cc', ...
                        'Callback', @(src, event) pozitiv(src), ...
                        'Parent', CasetaSemnal);
    
    VrCheckbox = uicontrol('Style', 'checkbox', ...
                               'Units', 'normalized', ...
                               'Position', [0.8 0.64 0.25 0.0255], ...
                               'String', 'Afișează Vr', ...
                               'BackgroundColor', '#f8e8cc', ...
                               'FontWeight', 'bold', ...
                               'Fontsize', 18, ...
                               'FontName', 'Courier New', ...
                               'Value', 0); %neselectat
    function pozitiv(src) %permite utilizarea doar a valorilor pozitive
    val = str2double(get(src, 'String'));
    if val < 0
        set(src, 'String', '1');  % valoarea 1 implicit
        val = 1; 
    else
        set(src, 'String', num2str(val));  
    end
    Tau(BR, BC, BTauVal);
    actual(); 
    end

    Tau(BR, BC, BTauVal);       % Calculul valorii lui tau
    function actual()
    
        U = str2double(get(BU, 'String'));  %se preiau valorile introduse de utilizator
        f = str2double(get(BT, 'String'));
        D = get(BD, 'Value'); %Value este folosit deoarece D corespunde unui buton slider
        Voff = str2double(get(BVoff, 'String'));
        Nrp = get(BN, 'Value');
        T = 1/f; %perioada e inversul frecventei

        if (R * C) <= T                                 %Verificarea conditiei circuitului integrator
            errordlg('R*C trebuie sa fie mai mare ca T.', 'Invalid Parameters');
            close(fig);
            return;
        end
       
        optiune = get(BN, 'String'); 
        N = str2double(optiune{Nrp}); 

       
        R = str2double(get(BR, 'String'));
        C = str2double(get(BC, 'String'));
        f = str2double(get(BT, 'String'));

        if (R * C) <= (1 / f)
            errordlg('Error: R*C trebuie să fie mai mare ca perioada.', 'Invalid Parameters');
            return; 
        end

        t1 = 0:(f/100):(N*f);                               %vector de timp
        si = (U + Voff) * square(2 * pi * (1/f) * t1, D);   %semnal dreptunghiular
        
        
        Vc = zeros(size(t1));               % Tensiunea pe condensator
        Vr = zeros(size(t1));               % Tensiunea pe rezistenta
        dt = t1(2) - t1(1);                 % interval mic pentru derivare
        for i = 2:length(t1)                %integrarea
            dVc = (1/(R*C)) * (si(i-1) - Vc(i-1)) * dt; 
            Vc(i) = Vc(i-1) + dVc; 
            Vr(i) = si(i-1) - Vc(i); 
        end
        
        
        subplot(3, 3, [2, 3]);             %grafic semnal de intrare
        cla;                               % eliminare date anterioare
        plot(t1, si, 'LineWidth', 2);
        title('Semnal de intrare dreptunghiular', 'FontSize', 12, 'FontWeight', 'Bold', 'Color', '#2d0101');
        ylabel('Ui [V]');
        xlabel('Frecvența [ Hz ]');
        ylim([-1.5 * max(U + Voff, 1), 1.5 * max(U + Voff, 1)]);     %marirea axei verticale
        grid on;
        
       
        subplot(3, 3, [5, 6]);             %grafic semnal de iesire
        cla;
        plot(t1, Vc, 'LineWidth', 2);
        hold on; %semnalul vr apare in functie de starea checkbox-ului

        if get(VrCheckbox, 'Value') 
            plot(t1, Vr, 'LineWidth', 2, 'LineStyle', '--'); 
            legend('Vc', 'Vr');
        else
            legend('Vc');
        end

        title('Semnal de ieșire - Tensiunea pe condensator (Vc)', 'FontSize', 12, 'FontWeight', 'Bold', 'Color', '#2d0101');
        ylabel('Vc [V]');
        xlabel('Timpul [ s ]');
        ylim([-1.5 * max(U + Voff, 1), 1.5 * max(U + Voff, 1)]);
        grid on;

       
        [maxValue, maxIndex] = max(Vc);             %valoarea maxima 
        plot(t1(maxIndex), maxValue, 'ro', 'MarkerSize', 10, 'DisplayName', 'Max Vc', 'MarkerFaceColor', '#8b0000', 'MarkerEdgeColor', '#f8e8cc');
        text(t1(maxIndex), maxValue, sprintf('Max: %.2f', maxValue), 'VerticalAlignment', 'bottom', 'HorizontalAlignment', 'right');
        
        hold off;
    end

    actual(); %prima initializare

    x = imread('RCIntegrator.jpg'); %introducerea unei imagini
    subplot(3, 3, [8, 9]); 
    image(x); 
    axis off;

end
